apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: parasol-agent
  title: Parasol AI IntelliSales
  description: Bootstraps a new Parsol Agent using a specified AI Model
  tags:
    - python
    - llamacpp
    - agent
    - ai
spec:
  owner: platform-engineering
  type: template

  parameters:
    - title: Basic Configuration
      required:
        - name
        - description
        - owner
        - model
      properties:
        name:
          title: Name
          type: string
          default: parasol-agent
          description: Unique name for the Component
          maxLength: 50
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          default: An Agentic application that uses a Model hosted by Red Hat OpenShift AI
          description: Description for the Component in the Software Catalog
          maxLength: 100
        owner:
          title: Owner
          type: string
          default: user:default/evanshortiss
          description: Owner of the resulting Component
          ui:field: OwnerPicker
          ui:options:
            allowArbitraryValues: false
            catalogFilter:
              kind: User
        model:
          title: Model
          description: The Model used by the Agent
          default: parasol/parasol-chat
          type: string
          enum:
            - parasol/parasol-chat-405b
            - parasol/parasol-chat-7b
            - parasol/parasol-agent-405b
            - parasol/parasol-agent-7b
            - parasol/parasol-corp
            - ibm-granite/granite-3.3-8b-instruct
            - ibm-granite/granite-8b-code-instruct-128k
            - google/gemma-3-27b-it
            - meta-llama/Llama-4-Scout-17B-16E-Instruct
    
    - title: Repository Information
      required:
        - hostType
        - repoOwner
        - repoName
        - branch
      properties:
        hostType:
          title: Host Type
          type: string
          enum:
            - GitHub
            - GitLab
          default: GitHub
        repoOwner:
          title: Repository Owner
          default: summit-demo
          type: string
          ui:help: The organization, user or project that this repo will belong to
        repoName:
          title: Repository Name
          type: string
          default: parasol-agent
        branch:
          title: Repository Default Branch
          type: string
          default: main
  steps:
    - id: template
      name: Generate Application
      action: fetch:template
      input:
        url: ./skeleton
        values: {}
    - id: publish
      name: Push Code to Git
      action: fetch:template
      input:
        url: ./skeleton
        values: {}
    - id: register
      name: Register Component in Catalog
      action: fetch:template
      input:
        url: ./skeleton
        values: {}
    - id: template-gitops-deployment
      name: Generate Deployment Manifests
      action: fetch:template
      input:
        url: ./skeleton
        values: {}
    - id: publishGitops
      name: Push Manifests to Git
      action: fetch:template
      input:
        url: ./skeleton
        values: {}
    - id: create-argocd-resources
      name: Create Argo CD Bootstrap Application
      action: fetch:template
      input:
        url: ./skeleton
        values: {}
  output:
    links:
      - title: Quarkus Application Repository
        url: https://foo.bar
      - title: Manifests Repository
        url: https://foo.bar
      - title: Open Component in Catalog
        icon: catalog
        url: https://foo.bar
